volumes:
  db-data:
  db-log:
  db-secrets:
services:
  api:
    build:
      context: .
      dockerfile: Containerfile
    profiles: [api]
    restart: on-failure:3
    environment:
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5172:5172"
    volumes:
      - .:/usr/src/app:z
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server
    restart: always
    user: root
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${DB_PASSWORD}
      MSSQL_COLLATION: SQL_Latin1_General_CP1_CI_AS_UTF8
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql/data
      - db-log:/var/opt/mssql/log
      - db-secrets:/var/opt/mssql/secrets
